# http://docs.travis-ci.com/user/languages/android/
language: android
sudo: false
jdk: oraclejdk8
os:
  - linux
android:
  components:
    - tools # needs to be first to get new package versions
    - build-tools-25.0.2
    - platform-tools
    - android-25

script: ./gradlew connectedAndroidTest